repos:
    - repo: local
      hooks:
          - id: check-jira-ticket
            name: Check Jira Ticket
            entry: python3 scripts/check_jira.py
            language: python
            stages: [commit-msg]

          - id: find-secrets
            name: Custom Secret Scanner
            entry: python3 scripts/find_secrets.py
            language: python
            files: \.(py|yaml|json|txt|env)$
            exclude: ^scripts/find_secrets\.py$
            stages: [pre-commit]
#  pre-commit install --hook-type commit-msg
#  pip install pre-commit
